version: '3'
services:
  docker-zabbix-agent:
    image: monitoringartist/dockbix-agent-xxl-limited:latest
    container_name: docker-zabbix-agent
    hostname: docker
    environment:
      ZA_Server: 192.168.0.56,172.19.0.1
      ZA_ServerActive: 192.168.0.56
    volumes:
      - /:/rootfs
      - /var/run:/var/run
    ports:
      - "10050:10050"
    restart: always